### PR TITLE
Jmp 957 81

### PR DESCRIPTION
**Pull request by jmarcpambrun**
to avaoid warning on deprecated function (drupal 9.5.7 Php 8.1)

### CODE REVIEW

**Comment by jmarcpambrun** [comment]
my first collaboration

**Comment by dungahk** [comment]
Hi @jmarcpambrun , this GitHub repository does not accept Pull Requests, if you want to contribute to Drupal, take a look on their guide: https://www.drupal.org/community/contributor-guide

**Comment by jmarcpambrun** [comment]
Warning on core

**Review by jmarcpambrun — COMMENTED** [review]
Solve isse on Warning 9.5.7

**Pull request closed without merging**
